# docker-compose.yml

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: salamtak
      POSTGRES_PASSWORD: password
      POSTGRES_DB: salamtak_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U salamtak"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgres://salamtak:password@db:5432/salamtak_db
    depends_on:
      - db
    ports:
      - "3000:3000"

  app_dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      DATABASE_URL: postgres://salamtak:password@db:5432/salamtak_db
    depends_on:
      - db
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/target
    command: ["cargo", "watch", "-x", "run"]

volumes:
  postgres_data:
